apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: project
  name: project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: project
    spec:
      containers:
      - image: project
        name: project
        imagePullPolicy: Never

        ports:
        - containerPort: 3000
        resources: {}
status: {}
